---
- hosts: all
  tasks: 
  - name: Installing Packages
    yum: name={{item.name}} state={{item.value}}
    with_items:
       - {name: 'httpd', value: 'absent'}
       - {name: 'git', value: 'absent'}
