---

  - name: VPC
    ec2_vpc:
      state: present
      cidr_block: 10.0.0.0/16
      resource_tags: { "Name": "{{ project_name }}", "Environment":"Dev" }
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key_ID }}"
      aws_secret_key: "{{ aws_secret_key }}"
      internet_gateway: yes
    register: vpc

  - name: VPC public subnet
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      vpc_id: "{{ vpc.vpc_id }}"
      cidr: 10.0.1.0/24
      aws_access_key: "{{ aws_access_key_ID }}"
      aws_secret_key: "{{ aws_secret_key }}"
      resource_tags:
        Name: Public
    register: public_network

  - name: VPC private subnet
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      aws_access_key: "{{ aws_access_key_ID }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ vpc.vpc_id }}"
      cidr: 10.0.2.0/24
      resource_tags:
        Name: Private
    register: private_network

  - name: VPC internet gateway
    ec2_vpc_igw:
      vpc_id: "{{ vpc.vpc_id }}"
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key_ID }}"
      aws_secret_key: "{{ aws_secret_key }}"
      state: present
    register: igw

  - name: VPC nat gw
    ec2_vpc_nat_gateway:
      region: "{{ region }}"
      wait: yes
      if_exist_do_not_create: true
      aws_access_key: "{{ aws_access_key_ID }}"
      aws_secret_key: "{{ aws_secret_key }}"
      state: present
      subnet_id: "{{ public_network.subnet.id }}"
    register: nat_gw

  - name: Public VMs security group
    ec2_group:
      name: public
      description: public internet machines
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key_ID }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ vpc.vpc_id }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 2377
          to_port: 2377
          cidr_ip: 10.0.0.0/16
    register: public_group

  - name: Private VMs security group
    ec2_group:
      name: private
      description: private internet machines
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key_ID }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ vpc.vpc_id }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 2377
          to_port: 2377
          cidr_ip: 0.0.0.0/0
    register: private_group

  - name: Public route table
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.vpc_id }}"
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key_ID }}"
      aws_secret_key: "{{ aws_secret_key }}"
      tags:
        Name: Public
      subnets:
        - "{{ public_network.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id }}"
        - dest: 10.0.0.0/16
          gateway_id: local

  - name: Private route table
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.vpc_id }}"
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key_ID }}"
      aws_secret_key: "{{ aws_secret_key }}"
      tags:
        Name: Private
      subnets:
        - "{{ private_network.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ nat_gw.nat_gateway_id }}"
        - dest: 10.0.0.0/16
          gateway_id: local

